"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var inquirer_1 = require("inquirer");
(0, inquirer_1.registerPrompt)("search-list", require("inquirer-search-list"));
(0, inquirer_1.registerPrompt)("search-checkbox", require("inquirer-search-checkbox"));
// prompt([
//   {
//     type: "search-list",
//     message: "Select topping",
//     name: "topping",
//     choices: [
//       "Pepperoni",
//       "Ham",
//       "Ground Meat",
//       "Bacon",
//       "Mozzarella",
//       "Bottle",
//     ],
//     validate: function (answer) {
//       if (answer === "Bottle") {
//         return `Whoops, ${answer} is not a real topping.`;
//       }
//       return true;
//     },
//   },
// ]);
var KDV = ["0", "1", "8", "18"];
// Available Material Types
var materials = [
    "0.3mm Silikon",
    "Ahşap",
    "Air Slim Silikon",
    "Altın",
    "Alüminyum",
    "Aynalı",
    "Aynalı Desenli - Cam",
    "Beyaz - Gold",
    "Cam",
    "Cam - Silikon",
    "Cam Tozu",
    "Deri",
    "Eva",
    "Flex",
    "Gerçek Deri",
    "Gümüş",
    "Kapaklı Kılıf",
    "Karbonfiber",
    "Kaucuk",
    "Kauçuk",
    "Keçe",
    "Koyu Pembe - Gold",
    "Kumaş",
    "Kılıf",
    "Likit",
    "Metal",
    "Mika",
    "Mıknatıs",
    "Nano Cam",
    "Neopren",
    "Nikel",
    "Nubuk",
    "Oleofobik Nano Kaplama",
    "PU Deri",
    "PVC",
    "Pencereli Kılıflar",
    "Plastik",
    "Polikarbon",
    "Polikarbonat",
    "Polimer",
    "Poliüretan",
    "Polycarbon",
    "Premium Metalik Malzeme",
    "Recycled",
    "Rubber",
    "Safir Silikon",
    "Sert Mika",
    "Sert Plastik",
    "Sert Plastik Kapak",
    "Sert Silikon",
    "Sierra Mavisi",
    "Silikon",
    "Suni Deri",
    "Süet",
    "TPU",
    "Tempered Cam",
    "Termoplastik Poliüretan",
    "Thermoplastic",
    "Şeffaf",
];
// Available Types of Phone Cases
var casesTypes = [
    "Aksesuar",
    "Ara Kapak",
    "Arka Kapak",
    "Arka Kılıf",
    "Askılı Kılıf",
    "Ekran Koruyucu",
    "Kapaklı Kılıf",
    "Kese",
    "Kol Bandı",
    "Sticker",
    "Çerçeve",
];
// Galaxy doesn't exist aghhh...
var phones = [
    "Galaxy  M01 Core",
    "Galaxy 21S",
    "Galaxy 7 Fold",
    "Galaxy A01",
    "Galaxy A01 Core",
    "Galaxy A01 US Version",
    "Galaxy A02",
    "Galaxy A02s",
    "Galaxy A03",
    "Galaxy A03 Core",
    "Galaxy A03S",
    "Galaxy A04",
    "Galaxy A04 4G",
    "Galaxy A04 Core",
    "Galaxy A04e",
    "Galaxy A04e 4G",
    "Galaxy A04s",
    "Galaxy A07",
    "Galaxy A10",
    "Galaxy A10e",
    "Galaxy A10s",
    "Galaxy A11",
    "Galaxy A12",
    "Galaxy A12 4G",
    "Galaxy A12 5G",
    "Galaxy A12 Nacho",
    "Galaxy A13",
    "Galaxy A13 4G",
    "Galaxy A13 5G",
    "Galaxy A14",
    "Galaxy A14 4G",
    "Galaxy A14 5G",
    "Galaxy A2 Core",
    "Galaxy A20",
    "Galaxy A20e",
    "Galaxy A20s",
    "Galaxy A21",
    "Galaxy A21s",
    "Galaxy A22",
    "Galaxy A22 4G",
    "Galaxy A22 5G",
    "Galaxy A22e",
    "Galaxy A23",
    "Galaxy A23 4G",
    "Galaxy A23 5G",
    "Galaxy A23e",
    "Galaxy A24",
    "Galaxy A24 4G",
    "Galaxy A24 5G",
    "Galaxy A25",
    "Galaxy A27",
    "Galaxy A3",
    "Galaxy A3 (2017)",
    "Galaxy A3 2015",
    "Galaxy A3 2016",
    "Galaxy A3 2017",
    "Galaxy A3 2018",
    "Galaxy A3 New",
    "Galaxy A30",
    "Galaxy A30 Plus",
    "Galaxy A30s",
    "Galaxy A31",
    "Galaxy A32",
    "Galaxy A32 4G",
    "Galaxy A32 4G2",
    "Galaxy A32 5G",
    "Galaxy A32 LTE",
    "Galaxy A33",
    "Galaxy A33 5G",
    "Galaxy A34",
    "Galaxy A34 5G",
    "Galaxy A40",
    "Galaxy A40s",
    "Galaxy A41",
    "Galaxy A42",
    "Galaxy A42 5G",
    "Galaxy A5",
    "Galaxy A5 (2017)",
    "Galaxy A5 2015",
    "Galaxy A5 2016",
    "Galaxy A5 2017",
    "Galaxy A5 2018",
    "Galaxy A5 New",
    "Galaxy A50",
    "Galaxy A50S",
    "Galaxy A51",
    "Galaxy A51 4G",
    "Galaxy A51 5G",
    "Galaxy A510",
    "Galaxy A514G",
    "Galaxy A51S",
    "Galaxy A52",
    "Galaxy A52 5G",
    "Galaxy A52s",
    "Galaxy A52s 5G",
    "Galaxy A53",
    "Galaxy A53 5G",
    "Galaxy A54",
    "Galaxy A54 5G",
    "Galaxy A6",
    "Galaxy A6 2018",
    "Galaxy A6 Plus",
    "Galaxy A6 Plus 2018",
    "Galaxy A60",
    "Galaxy A6S",
    "Galaxy A7",
    "Galaxy A7 (2017)",
    "Galaxy A7 (2018)",
    "Galaxy A7 2015",
    "Galaxy A7 2016",
    "Galaxy A7 2017",
    "Galaxy A7 2018",
    "Galaxy A7 2019",
    "Galaxy A7 New",
    "Galaxy A70",
    "Galaxy A70E",
    "Galaxy A70s",
    "Galaxy A71",
    "Galaxy A71 4G",
    "Galaxy A71 5G",
    "Galaxy A72",
    "Galaxy A72 5G",
    "Galaxy A73",
    "Galaxy A73 5G",
    "Galaxy A74",
    "Galaxy A750",
    "Galaxy A8",
    "Galaxy A8 (2018)",
    "Galaxy A8 2015",
    "Galaxy A8 2016",
    "Galaxy A8 2018",
    "Galaxy A8 Plus",
    "Galaxy A8 Plus (2018)",
    "Galaxy A8 Plus 2018",
    "Galaxy A8 Star",
    "Galaxy A80",
    "Galaxy A81",
    "Galaxy A82",
    "Galaxy A82 5G",
    "Galaxy A8S",
    "Galaxy A9",
    "Galaxy A9 (2018)",
    "Galaxy A9 2016",
    "Galaxy A9 2018",
    "Galaxy A9 2019",
    "Galaxy A9 Pro",
    "Galaxy A9 Pro 2016",
    "Galaxy A9 Pro 2019",
    "Galaxy A9 Star",
    "Galaxy A9 Star Lite",
    "Galaxy A90",
    "Galaxy A90 5G",
    "Galaxy A91",
    "Galaxy A9S",
    "Galaxy Ace",
    "Galaxy Ace 2",
    "Galaxy Ace 3",
    "Galaxy Ace 4",
    "Galaxy Ace 5830",
    "Galaxy Ace S5830",
    "Galaxy Alpha",
    "Galaxy Beam",
    "Galaxy Beam i8530",
    "Galaxy Buds Live",
    "Galaxy C5",
    "Galaxy C5 Pro",
    "Galaxy C7",
    "Galaxy C7 Core",
    "Galaxy C7 Pro",
    "Galaxy C8",
    "Galaxy C9",
    "Galaxy C9 Pro",
    "Galaxy Chat",
    "Galaxy Core",
    "Galaxy Core 2",
    "Galaxy Core G350",
    "Galaxy Core Plus",
    "Galaxy Core Prime",
    "Galaxy Core Prime G360",
    "Galaxy Core i8262",
    "Galaxy Cover 4",
    "Galaxy Duo",
    "Galaxy Duo S7562",
    "Galaxy E5",
    "Galaxy E7",
    "Galaxy F02S",
    "Galaxy F04 4G",
    "Galaxy F12",
    "Galaxy F13",
    "Galaxy F13 4G",
    "Galaxy F14",
    "Galaxy F14 5G",
    "Galaxy F23",
    "Galaxy F23 5G",
    "Galaxy F41",
    "Galaxy F42",
    "Galaxy F52",
    "Galaxy F52 5G",
    "Galaxy F62",
    "Galaxy Fame S6810",
    "Galaxy Feel 2",
    "Galaxy Fold 3",
    "Galaxy Fold 4",
    "Galaxy G720 Grand Max",
    "Galaxy Gear S3",
    "Galaxy Gio",
    "Galaxy Gio S5660",
    "Galaxy Grand",
    "Galaxy Grand 2",
    "Galaxy Grand 2 Duos G7106",
    "Galaxy Grand 2 G7102",
    "Galaxy Grand 3 Duos",
    "Galaxy Grand Duos",
    "Galaxy Grand Duos i9082",
    "Galaxy Grand Max G7200",
    "Galaxy Grand Mega",
    "Galaxy Grand Neo",
    "Galaxy Grand Neo Plus",
    "Galaxy Grand Prime",
    "Galaxy Grand Prime G530",
    "Galaxy Grand Prime Plus",
    "Galaxy Grand Prime Pro",
    "Galaxy J1",
    "Galaxy J1 2016",
    "Galaxy J1 Ace",
    "Galaxy J1 Mini",
    "Galaxy J1 Mini Prime",
    "Galaxy J2",
    "Galaxy J2 2016",
    "Galaxy J2 Core",
    "Galaxy J2 Prime",
    "Galaxy J2 Pro",
    "Galaxy J2 Pro 2018",
    "Galaxy J3",
    "Galaxy J3 2015",
    "Galaxy J3 2016",
    "Galaxy J3 2017",
    "Galaxy J3 Prime",
    "Galaxy J3 Pro",
    "Galaxy J3 Pro 2017",
    "Galaxy J330",
    "Galaxy J330 Pro",
    "Galaxy J4",
    "Galaxy J4 2018",
    "Galaxy J4 Core",
    "Galaxy J4 Plus",
    "Galaxy J4 Plus 2018",
    "Galaxy J4 Prime",
    "Galaxy J5",
    "Galaxy J5 2015",
    "Galaxy J5 2016",
    "Galaxy J5 2017",
    "Galaxy J5 Core",
    "Galaxy J5 Prime",
    "Galaxy J5 Pro",
    "Galaxy J5 Pro 2016",
    "Galaxy J5 Pro 2017",
    "Galaxy J5 Pro 2018",
    "Galaxy J510",
    "Galaxy J530",
    "Galaxy J530 Pro",
    "Galaxy J6",
    "Galaxy J6 2018",
    "Galaxy J6 Plus",
    "Galaxy J6 Plus 2018",
    "Galaxy J6 Prime",
    "Galaxy J7",
    "Galaxy J7 2015",
    "Galaxy J7 2016",
    "Galaxy J7 2017",
    "Galaxy J7 2018",
    "Galaxy J7 Core",
    "Galaxy J7 Duo",
    "Galaxy J7 Max",
    "Galaxy J7 Nxt",
    "Galaxy J7 Plus",
    "Galaxy J7 Prime",
    "Galaxy J7 Prime 2",
    "Galaxy J7 Pro",
    "Galaxy J7 Pro 2016",
    "Galaxy J7 Pro 2017",
    "Galaxy J710",
    "Galaxy J730",
    "Galaxy J730 Pro",
    "Galaxy J8",
    "Galaxy J8 2018",
    "Galaxy J8 Plus",
    "Galaxy Jean",
    "Galaxy Jump 2",
    "Galaxy K Zoom",
    "Galaxy M01",
    "Galaxy M01 Core",
    "Galaxy M01S",
    "Galaxy M02",
    "Galaxy M02S",
    "Galaxy M04",
    "Galaxy M10",
    "Galaxy M10s",
    "Galaxy M11",
    "Galaxy M12",
    "Galaxy M13",
    "Galaxy M13 4G",
    "Galaxy M13 5G",
    "Galaxy M14",
    "Galaxy M14 5G",
    "Galaxy M20",
    "Galaxy M20S",
    "Galaxy M21",
    "Galaxy M21S",
    "Galaxy M22",
    "Galaxy M23",
    "Galaxy M23 5G",
    "Galaxy M24",
    "Galaxy M25",
    "Galaxy M30",
    "Galaxy M30s",
    "Galaxy M31",
    "Galaxy M31s",
    "Galaxy M32",
    "Galaxy M32 4G",
    "Galaxy M32 5G",
    "Galaxy M33",
    "Galaxy M33 5G",
    "Galaxy M34",
    "Galaxy M40",
    "Galaxy M40s",
    "Galaxy M42 5G",
    "Galaxy M51",
    "Galaxy M52",
    "Galaxy M52 5G",
    "Galaxy M53",
    "Galaxy M53 5G",
    "Galaxy M54",
    "Galaxy M62",
    "Galaxy M80s",
    "Galaxy Mega",
    "Galaxy Mega 2",
    "Galaxy Mega 2 G750",
    "Galaxy Mega 5.8",
    "Galaxy Mega 6.3",
    "Galaxy Mini",
    "Galaxy Mini S5570",
    "Galaxy Nexus",
    "Galaxy Nexus i9250",
    "Galaxy Note",
    "Galaxy Note 1",
    "Galaxy Note 10",
    "Galaxy Note 10 Lite",
    "Galaxy Note 10 PluS 5G",
    "Galaxy Note 10 Plus",
    "Galaxy Note 10 Pro",
    "Galaxy Note 10+ Plus",
    "Galaxy Note 12",
    "Galaxy Note 2",
    "Galaxy Note 20",
    "Galaxy Note 20 5G",
    "Galaxy Note 20 Plus",
    "Galaxy Note 20 Ultra",
    "Galaxy Note 20 Ultra 5G",
    "Galaxy Note 3",
    "Galaxy Note 3 Neo",
    "Galaxy Note 4",
    "Galaxy Note 4 Edge",
    "Galaxy Note 5",
    "Galaxy Note 5 Edge",
    "Galaxy Note 7",
    "Galaxy Note 8",
    "Galaxy Note 9",
    "Galaxy Note 9 Plus",
    "Galaxy Note Edge",
    "Galaxy Note FE",
    "Galaxy Note N7000",
    "Galaxy Note10 +",
    "Galaxy On Max",
    "Galaxy On5",
    "Galaxy On5 2016",
    "Galaxy On6",
    "Galaxy On7",
    "Galaxy On7 2016",
    "Galaxy On7 Prime",
    "Galaxy On8",
    "Galaxy Pro",
    "Galaxy Quantum 2",
    "Galaxy S Advance",
    "Galaxy S Advance i9070",
    "Galaxy S Duo",
    "Galaxy S Duos 7560 7580",
    "Galaxy S Duos 7562 7582",
    "Galaxy S Entry",
    "Galaxy S Plus",
    "Galaxy S Plus i9001",
    "Galaxy S10",
    "Galaxy S10 5G",
    "Galaxy S10 Lite",
    "Galaxy S10 Plus",
    "Galaxy S10+",
    "Galaxy S10E Plus",
    "Galaxy S10e",
    "Galaxy S10s",
    "Galaxy S11",
    "Galaxy S11 Plus",
    "Galaxy S11 Ultra",
    "Galaxy S11e",
    "Galaxy S2",
    "Galaxy S20",
    "Galaxy S20 5G",
    "Galaxy S20 FE",
    "Galaxy S20 FE 5G",
    "Galaxy S20 Lite",
    "Galaxy S20 PluS 5G",
    "Galaxy S20 Plus",
    "Galaxy S20 Ultra",
    "Galaxy S20 Ultra 5G",
    "Galaxy S20+",
    "Galaxy S20+ Plus",
    "Galaxy S21",
    "Galaxy S21 5G",
    "Galaxy S21 FE",
    "Galaxy S21 FE 5G",
    "Galaxy S21 PluS 5G",
    "Galaxy S21 Plus",
    "Galaxy S21 Ultra",
    "Galaxy S21 Ultra 5G",
    "Galaxy S21+",
    "Galaxy S21+ Plus",
    "Galaxy S22",
    "Galaxy S22 5G",
    "Galaxy S22 FE",
    "Galaxy S22 Plus",
    "Galaxy S22 Plus 5G",
    "Galaxy S22 Pro",
    "Galaxy S22 Ultra",
    "Galaxy S22 Ultra 5G",
    "Galaxy S22+",
    "Galaxy S22+ 5G",
    "Galaxy S22+ Plus",
    "Galaxy S23",
    "Galaxy S23 5G",
    "Galaxy S23 Plus",
    "Galaxy S23 Plus 5G",
    "Galaxy S23 Ultra",
    "Galaxy S23 Ultra 5G",
    "Galaxy S23+",
    "Galaxy S24",
    "Galaxy S3",
    "Galaxy S3 Mini",
    "Galaxy S3 Neo",
    "Galaxy S30",
    "Galaxy S30 Plus",
    "Galaxy S30 Ultra",
    "Galaxy S4",
    "Galaxy S4 Active",
    "Galaxy S4 Mini",
    "Galaxy S4 Zoom",
    "Galaxy S4 i9500",
    "Galaxy S5",
    "Galaxy S5 Mini",
    "Galaxy S5 Zoom",
    "Galaxy S6",
    "Galaxy S6 Edge",
    "Galaxy S6 Edge Plus",
    "Galaxy S7",
    "Galaxy S7 Active",
    "Galaxy S7 Edge",
    "Galaxy S7 Edge Plus",
    "Galaxy S8",
    "Galaxy S8 Active",
    "Galaxy S8 Plus",
    "Galaxy S9",
    "Galaxy S9 Plus",
    "Galaxy S9+",
    "Galaxy Star 2",
    "Galaxy Tab",
    "Galaxy Tab S5e",
    "Galaxy Tab S8 Ultra",
    "Galaxy Trend",
    "Galaxy Trend Lite",
    "Galaxy Trend Lite S7390",
    "Galaxy Trend Plus",
    "Galaxy Trend Plus S7580",
    "Galaxy W",
    "Galaxy W21",
    "Galaxy Watch",
    "Galaxy Wave 2",
    "Galaxy Wide 3",
    "Galaxy Win",
    "Galaxy Wonder",
    "Galaxy X Cover 5",
    "Galaxy X Cover Pro",
    "Galaxy XCover6 Pro",
    "Galaxy Xcover 4",
    "Galaxy Xcover 4s",
    "Galaxy Xcover 5",
    "Galaxy Xcover 6 Pro",
    "Galaxy Xcover Pro",
    "Galaxy Xcover Pro 2",
    "Galaxy Xcover Pro 6",
    "Galaxy Y",
    "Galaxy Y Pro",
    "Galaxy Y S5360",
    "Galaxy Z Filp 3 5G",
    "Galaxy Z Flip",
    "Galaxy Z Flip 3",
    "Galaxy Z Flip 3 5G",
    "Galaxy Z Flip 4",
    "Galaxy Z Flip 4 5G",
    "Galaxy Z Flip 5",
    "Galaxy Z Flip2",
    "Galaxy Z Flip3 5g",
    "Galaxy Z Flip4",
    "Galaxy Z Flip4 5G",
    "Galaxy Z Fold 2",
    "Galaxy Z Fold 3",
    "Galaxy Z Fold 3 5G",
    "Galaxy Z Fold 4",
    "Galaxy Z Fold 4 5G",
    "Galaxy Z Fold2",
    "Galaxy Z Fold2 5G",
    "Galaxy Z1",
    "OPPO A15",
    "OPPO A15S",
    "OPPO A5 2020",
    "OPPO A5S",
    "OPPO A72",
    "OPPO A73",
    "OPPO A9",
    "OPPO A9 2020",
    "OPPO F11",
    "Oppo",
    "Oppo A1 Pro",
    "Oppo A13",
    "Oppo A17",
    "Oppo A54",
    "Oppo A54 4G",
    "Oppo A55 5G",
    "Oppo A74",
    "Oppo A74 4G",
    "Oppo A7X",
    "Oppo A83",
    "Oppo A91",
    "Oppo A92",
    "Oppo A94",
    "Oppo AX7",
    "Oppo F3",
    "Oppo Find X2",
    "Oppo Find X6",
    "Oppo Find X6 Pro",
    "Oppo RX17 Neo",
    "Oppo RX17 Pro",
    "Oppo Reno 10X Zoom",
    "Oppo Reno 2Z",
    "Oppo Reno 3",
    "Oppo Reno 3 Pro",
    "Oppo Reno 4 Lite",
    "Oppo Reno 4 Pro",
    "Oppo Reno 5",
    "Oppo Reno 5 Pro 5G",
    "Oppo Reno 6",
    "Oppo Reno 6 Pro",
    "Oppo Reno 6 Pro Plus",
    "Oppo Reno Z",
    "Oppo Reno8 5G",
    "Oppo Reno8 Lite",
    "Oppo Reno8 T 4G",
    "Oppo Reno8 T 5G",
    "Oppo Reno9",
    "Redmi  Note 11S",
    "Redmi 10",
    "Redmi 10 2022",
    "Redmi 10 5G",
    "Redmi 10 Prime",
    "Redmi 10A",
    "Redmi 10C",
    "Redmi 10C 4G",
    "Redmi 10X",
    "Redmi 10X Pro 5G",
    "Redmi 11 Prime",
    "Redmi 11 Prime 5G",
    "Redmi 12C",
    "Redmi 1S",
    "Redmi 2 Pro",
    "Redmi 20x",
    "Redmi 2S",
    "Redmi 2X",
    "Redmi 3",
    "Redmi 3 Pro",
    "Redmi 3S",
    "Redmi 3X",
    "Redmi 4",
    "Redmi 4 Prime",
    "Redmi 4 Pro",
    "Redmi 4A",
    "Redmi 4X",
    "Redmi 4X - Redmi 4",
    "Redmi 5",
    "Redmi 5 Plus",
    "Redmi 5A",
    "Redmi 5X",
    "Redmi 6",
    "Redmi 6 Pro",
    "Redmi 6A",
    "Redmi 6X",
    "Redmi 7",
    "Redmi 7A",
    "Redmi 8",
    "Redmi 8A",
    "Redmi 8A Pro",
    "Redmi 9",
    "Redmi 9 Power",
    "Redmi 9 Prime",
    "Redmi 9 Pro Max",
    "Redmi 9A",
    "Redmi 9AT",
    "Redmi 9C",
    "Redmi 9C NFC",
    "Redmi 9T",
    "Redmi 9i Sport",
    "Redmi 9İ",
    "Redmi A1",
    "Redmi A1 4G",
    "Redmi A1 Plus",
    "Redmi A1 Plus 4G",
    "Redmi A2",
    "Redmi A2 Plus",
    "Redmi Go",
    "Redmi K20",
    "Redmi K20 Pro",
    "Redmi K20 Pro Premium",
    "Redmi K30",
    "Redmi K30 5G",
    "Redmi K30 Pro",
    "Redmi K30 Pro Zoom",
    "Redmi K30 Ultra",
    "Redmi K30S",
    "Redmi K30i",
    "Redmi K34",
    "Redmi K40",
    "Redmi K40 Gaming",
    "Redmi K40 Pro",
    "Redmi K40 Pro Plus",
    "Redmi K40 Pro+",
    "Redmi K40S",
    "Redmi K50",
    "Redmi K50 Gaming",
    "Redmi K50 Pro",
    "Redmi K50 Ultra",
    "Redmi K50i",
    "Redmi K60",
    "Redmi K60 Pro",
    "Redmi K60E",
    "Redmi Note",
    "Redmi Note 10",
    "Redmi Note 10 4G",
    "Redmi Note 10 5G",
    "Redmi Note 10 JE",
    "Redmi Note 10 Lite",
    "Redmi Note 10 Pro",
    "Redmi Note 10 Pro 4G",
    "Redmi Note 10 Pro 5G",
    "Redmi Note 10 Pro Max",
    "Redmi Note 10T",
    "Redmi Note 10T 5G",
    "Redmi Note 10s",
    "Redmi Note 11",
    "Redmi Note 11 4G",
    "Redmi Note 11 5G",
    "Redmi Note 11 Global",
    "Redmi Note 11 Pro",
    "Redmi Note 11 Pro 4G",
    "Redmi Note 11 Pro 5G",
    "Redmi Note 11 Pro Plus",
    "Redmi Note 11 Pro Plus 5g",
    "Redmi Note 11 S",
    "Redmi Note 11 SE",
    "Redmi Note 11C",
    "Redmi Note 11E",
    "Redmi Note 11E 5G",
    "Redmi Note 11E Pro",
    "Redmi Note 11R",
    "Redmi Note 11S",
    "Redmi Note 11T",
    "Redmi Note 11T 5G",
    "Redmi Note 11T Pro",
    "Redmi Note 11T Pro 5G",
    "Redmi Note 11T Pro Plus",
    "Redmi Note 11T Pro+",
    "Redmi Note 12",
    "Redmi Note 12 4G",
    "Redmi Note 12 5G",
    "Redmi Note 12 Pro",
    "Redmi Note 12 Pro 4G",
    "Redmi Note 12 Pro 5G",
    "Redmi Note 12 Pro Plus",
    "Redmi Note 12 Pro+",
    "Redmi Note 12 Pro+ 5G",
    "Redmi Note 12 Turbo",
    "Redmi Note 12S",
    "Redmi Note 12T",
    "Redmi Note 12T Pro",
    "Redmi Note 13",
    "Redmi Note 2",
    "Redmi Note 3",
    "Redmi Note 3 Pro",
    "Redmi Note 4",
    "Redmi Note 4A",
    "Redmi Note 4X",
    "Redmi Note 5",
    "Redmi Note 5 Plus",
    "Redmi Note 5 Pro",
    "Redmi Note 5A",
    "Redmi Note 5A Prime",
    "Redmi Note 5A Pro",
    "Redmi Note 6",
    "Redmi Note 6 Pro",
    "Redmi Note 7",
    "Redmi Note 7 Pro",
    "Redmi Note 7S",
    "Redmi Note 8",
    "Redmi Note 8 Pro",
    "Redmi Note 8T",
    "Redmi Note 9",
    "Redmi Note 9 4G",
    "Redmi Note 9 5G",
    "Redmi Note 9 Pro",
    "Redmi Note 9 Pro 5G",
    "Redmi Note 9 Pro Max",
    "Redmi Note 9A",
    "Redmi Note 9C",
    "Redmi Note 9S",
    "Redmi Note 9T",
    "Redmi Note 9T Pro",
    "Redmi Pro",
    "Redmi S2",
    "Redmi Y1",
    "Redmi Y1 Lite",
    "Redmi Y2",
    "Redmi Y3",
    "Reno",
    "Reno 10X",
    "Reno 10X Zoom",
    "Reno 2",
    "Reno 2F",
    "Reno 2Z",
    "Reno 2Z 2019",
    "Reno 3",
    "Reno 3 5G",
    "Reno 3 Pro",
    "Reno 3 Pro 5G",
    "Reno 3a",
    "Reno 4",
    "Reno 4 5G",
    "Reno 4 Lite",
    "Reno 4 Pro",
    "Reno 4 Pro 4G",
    "Reno 4 Pro 5G",
    "Reno 4 SE",
    "Reno 4F",
    "Reno 4G",
    "Reno 4Z",
    "Reno 5",
    "Reno 5 4G",
    "Reno 5 5G",
    "Reno 5 K",
    "Reno 5 Lite",
    "Reno 5 Pro",
    "Reno 5 Pro 5G",
    "Reno 5 Pro Plus",
    "Reno 5 Pro+",
    "Reno 5A",
    "Reno 5F",
    "Reno 5G",
    "Reno 5Z",
    "Reno 6",
    "Reno 6 4G",
    "Reno 6 5G",
    "Reno 6 Lite",
    "Reno 6 Pro",
    "Reno 6 Pro 5G",
    "Reno 6 Pro Plus",
    "Reno 6Z",
    "Reno 7",
    "Reno 7 4G",
    "Reno 7 5G",
    "Reno 7 Lite",
    "Reno 7 Lite 5G",
    "Reno 7 Pro",
    "Reno 7 Pro 5G",
    "Reno 7 SE",
    "Reno 7 SE 5G",
    "Reno 7Z",
    "Reno 7Z 5G",
    "Reno 8",
    "Reno 8 5G",
    "Reno 8 Lite",
    "Reno 8 Lite 5G",
    "Reno 8 Pro",
    "Reno 8 Pro 5G",
    "Reno 8T 4G",
    "Reno 8T 5G",
    "Reno 9",
    "Reno 9 Pro",
    "Reno 9 Pro Plus",
    "Reno A",
    "Reno A54 4G",
    "Reno ACE",
    "Reno ACE 2",
    "Reno Z",
    "Reno2 F",
    "Reno2 Z",
    "Reno3",
    "Reno3 A",
    "Reno3 Youth",
    "Reno4",
    "Reno4 Pro",
    "Reno4 SE",
    "Reno4 Z 5G",
    "Reno5 4G",
    "Reno5 K",
    "Reno5 Lite",
    "Reno5 Pro",
    "Reno5 Z",
    "Reno7 Pro 5G",
    "Reno7 Z",
    "Reno8 Pro+",
    "Samsung (Tüm Modeller)",
    "Samsung Galaxy A03S",
    "Samsung Galaxy A04E",
    "Samsung Galaxy A52",
    "Samsung Galaxy A72",
    "Samsung Galaxy Ace Plus S7500",
    "Samsung Galaxy Corby 2 S3850",
    "Samsung Galaxy Core",
    "Samsung Galaxy E250",
    "Samsung Galaxy F52 5G",
    "Samsung Galaxy M13",
    "Samsung Galaxy M22",
    "Samsung Galaxy S İ9000",
    "Samsung Galaxy S21 FE 5G",
    "Samsung Galaxy S22",
    "Samsung Galaxy S22 Plus",
    "Samsung Galaxy S22 Ultra",
    "Samsung Galaxy S23 Plus",
    "Samsung Galaxy S23 Ultra",
    "Samsung Galaxy S3350",
    "Samsung Galaxy S3600",
    "Samsung Galaxy S5230 Star",
    "Samsung Galaxy S7 Plus",
    "Samsung Galaxy Wave S5253",
    "Samsung Galaxy Wave S7233",
    "Samsung Galaxy Wave S8500",
    "Samsung Galaxy Xcover 4",
    "Samsung Galaxy Z Flip",
    "Xiaomi 11",
    "Xiaomi 11 Lite",
    "Xiaomi 11 Pro",
    "Xiaomi 11 Ultra",
    "Xiaomi 11T",
    "Xiaomi 11T Pro",
    "Xiaomi 12",
    "Xiaomi 12 Lite",
    "Xiaomi 12 Pro",
    "Xiaomi 12 Ultra",
    "Xiaomi 12S",
    "Xiaomi 12S Ultra",
    "Xiaomi 12T",
    "Xiaomi 12T Pro",
    "Xiaomi 12T/12T Pro",
    "Xiaomi 12X",
    "Xiaomi 13",
    "Xiaomi 13 Lite",
    "Xiaomi 13 Pro",
    "Xiaomi 13 Ultra",
    "Xiaomi C",
    "Xiaomi Civi",
    "Xiaomi Civi 2",
    "Xiaomi Mi 11T 5G",
    "Xiaomi Mi A3",
    "Xiaomi Mi Max 2",
    "Xiaomi Mi Pad 5",
    "Xiaomi Mi Poco X3 GT",
    "Xiaomi Mix 4",
    "Xiaomi Note 8",
    "Xiaomi Poco C40",
    "Xiaomi Redmi 12C",
    "Xiaomi Redmi K40 Gaming",
    "Xiaomi Redmi Note 11T Pro+ 5G",
    "Xiaomi Redmi Note 12",
    "Xiaomi Redmi Note 12 4G",
    "i9082 Galaxy Grand",
    "iPhone",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 Max",
    "iPhone 12 Mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13",
    "iPhone 13 Max",
    "iPhone 13 Mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Max",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 3GS",
    "iPhone 4",
    "iPhone 4S",
    "iPhone 5",
    "iPhone 5C",
    "iPhone 5S",
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 6S",
    "iPhone 6S Plus",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 7/8",
    "iPhone 7/8 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone Max",
    "iPhone SE",
    "iPhone SE (2022)",
    "iPhone SE 2",
    "iPhone SE 2020",
    "iPhone SE 2022",
    "iPhone SE 3 2022",
    "iPhone SE3",
    "iPhone X",
    "iPhone X/XS",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS MaiPhone X",
    "iPhone XS Max",
    "iPhone XS Plus",
];
var crap = [
    "Galaxy A01",
    "Galaxy A01 Core",
    "Galaxy A02",
    "Galaxy A02s",
    "Galaxy A03",
    "Galaxy A03 Core",
    "Galaxy A03 Pro",
    "Galaxy A03S",
    "Galaxy A04",
    "Galaxy A04e",
    "Galaxy A04s",
    "Galaxy A10",
    "Galaxy A10e",
    "Galaxy A10s",
    "Galaxy A11",
    "Galaxy A12",
    "Galaxy A13",
    "Galaxy A13 4G",
    "Galaxy A13 5G",
    "Galaxy A14",
    "Galaxy A14 4G",
    "Galaxy A14 5G",
    "Galaxy A2 Core",
    "Galaxy A20",
    "Galaxy A20 - A30",
    "Galaxy A20 Pro",
    "Galaxy A20e",
    "Galaxy A20s",
    "Galaxy A21",
    "Galaxy A21s",
    "Galaxy A22",
    "Galaxy A22 4G",
    "Galaxy A22 5G",
    "Galaxy A22e",
    "Galaxy A23",
    "Galaxy A23 4G",
    "Galaxy A23 5G",
    "Galaxy A23 5G / 4G",
    "Galaxy A23e",
    "Galaxy A24",
    "Galaxy A24 4G",
    "Galaxy A25",
    "Galaxy A27",
    "Galaxy A3",
    "Galaxy A3 (2016)",
    "Galaxy A3 2016",
    "Galaxy A3 2017",
    "Galaxy A30",
    "Galaxy A30s",
    "Galaxy A31",
    "Galaxy A32",
    "Galaxy A32 4G",
    "Galaxy A32 5G",
    "Galaxy A33",
    "Galaxy A33 5G",
    "Galaxy A34",
    "Galaxy A34 5G",
    "Galaxy A40",
    "Galaxy A41",
    "Galaxy A42",
    "Galaxy A42 5G",
    "Galaxy A5",
    "Galaxy A5 (2016)",
    "Galaxy A5 2016",
    "Galaxy A5 2017",
    "Galaxy A50",
    "Galaxy A50S",
    "Galaxy A50S Galaxy A30S",
    "Galaxy A50s / A30s / A50",
    "Galaxy A51",
    "Galaxy A52",
    "Galaxy A52 5G",
    "Galaxy A52s",
    "Galaxy A52s 5G",
    "Galaxy A53",
    "Galaxy A53 5G",
    "Galaxy A54",
    "Galaxy A54 5G",
    "Galaxy A6",
    "Galaxy A6 2018",
    "Galaxy A6 Plus",
    "Galaxy A6 Plus 2018",
    "Galaxy A60",
    "Galaxy A6S",
    "Galaxy A7",
    "Galaxy A7 (2016)",
    "Galaxy A7 2016",
    "Galaxy A7 2017",
    "Galaxy A7 2018",
    "Galaxy A70",
    "Galaxy A70s",
    "Galaxy A71",
    "Galaxy A72",
    "Galaxy A72 5G",
    "Galaxy A73",
    "Galaxy A73 5G",
    "Galaxy A74",
    "Galaxy A8",
    "Galaxy A8 (2018)",
    "Galaxy A8 2016",
    "Galaxy A8 2018",
    "Galaxy A8 Plus",
    "Galaxy A8 Plus (2018)",
    "Galaxy A8 Plus 2018",
    "Galaxy A80",
    "Galaxy A81",
    "Galaxy A81 (Note 10 Lite)",
    "Galaxy A82",
    "Galaxy A9",
    "Galaxy A9 (2016)",
    "Galaxy A9 2018",
    "Galaxy A90",
    "Galaxy A91",
    "Galaxy Ace 3",
    "Galaxy Ace 4",
    "Galaxy Alpha",
    "Galaxy C5",
    "Galaxy C5 Pro",
    "Galaxy C7",
    "Galaxy C7 Pro",
    "Galaxy C7010 C7 Pro",
    "Galaxy C8",
    "Galaxy C9 Pro",
    "Galaxy Core",
    "Galaxy Core 2",
    "Galaxy Core Prime",
    "Galaxy E5",
    "Galaxy E7",
    "Galaxy F02S",
    "Galaxy F12",
    "Galaxy F41",
    "Galaxy F52",
    "Galaxy F52 5G",
    "Galaxy F62",
    "Galaxy G530",
    "Galaxy Grand 9082",
    "Galaxy Grand Duos",
    "Galaxy Grand Prime",
    "Galaxy Grand Prime Pro",
    "Galaxy J1",
    "Galaxy J1 Ace",
    "Galaxy J1 Mini Prime",
    "Galaxy J2",
    "Galaxy J2 Core",
    "Galaxy J2 Prime",
    "Galaxy J2 Pro",
    "Galaxy J2 Pro 2018",
    "Galaxy J3",
    "Galaxy J3 Pro",
    "Galaxy J4",
    "Galaxy J4 Plus",
    "Galaxy J5",
    "Galaxy J5 2016",
    "Galaxy J5 Prime",
    "Galaxy J5 Pro",
    "Galaxy J6",
    "Galaxy J6 Plus",
    "Galaxy J7",
    "Galaxy J7 2016",
    "Galaxy J7 Core",
    "Galaxy J7 Duo",
    "Galaxy J7 Max",
    "Galaxy J7 Prime",
    "Galaxy J7 Pro",
    "Galaxy J730 Pro",
    "Galaxy J8",
    "Galaxy M01",
    "Galaxy M01 Core",
    "Galaxy M02",
    "Galaxy M10",
    "Galaxy M10s",
    "Galaxy M11",
    "Galaxy M12",
    "Galaxy M13",
    "Galaxy M14",
    "Galaxy M14 5G",
    "Galaxy M20",
    "Galaxy M21",
    "Galaxy M21S",
    "Galaxy M22",
    "Galaxy M23",
    "Galaxy M23 5G",
    "Galaxy M24",
    "Galaxy M30",
    "Galaxy M30s",
    "Galaxy M31",
    "Galaxy M31s",
    "Galaxy M32",
    "Galaxy M33",
    "Galaxy M33 5G",
    "Galaxy M34",
    "Galaxy M40",
    "Galaxy M51",
    "Galaxy M52",
    "Galaxy M52 5G",
    "Galaxy M53",
    "Galaxy M53 5G",
    "Galaxy M54",
    "Galaxy M62",
    "Galaxy Note 10",
    "Galaxy Note 10 Lite",
    "Galaxy Note 10 Plus",
    "Galaxy Note 2",
    "Galaxy Note 20",
    "Galaxy Note 20 5G",
    "Galaxy Note 20 Ultra",
    "Galaxy Note 20 Ultra 5G",
    "Galaxy Note 7",
    "Galaxy Note 8",
    "Galaxy Note 9",
    "Galaxy S10",
    "Galaxy S10 Lite",
    "Galaxy S10 Plus",
    "Galaxy S10 Pro",
    "Galaxy S10e",
    "Galaxy S20",
    "Galaxy S20 FE",
    "Galaxy S20 Lite",
    "Galaxy S20 Plus",
    "Galaxy S20 Ultra",
    "Galaxy S21",
    "Galaxy S21 5G",
    "Galaxy S21 FE",
    "Galaxy S21 Plus",
    "Galaxy S21 Ultra",
    "Galaxy S22",
    "Galaxy S22 5G",
    "Galaxy S22 FE",
    "Galaxy S22 Plus",
    "Galaxy S22 Pro",
    "Galaxy S22 Ultra",
    "Galaxy S23",
    "Galaxy S23 5G",
    "Galaxy S23 Plus",
    "Galaxy S23 Plus 5G",
    "Galaxy S23 Ultra",
    "Galaxy S23 Ultra 5G",
    "Galaxy S23+",
    "Galaxy S3",
    "Galaxy S3 Mini",
    "Galaxy S30",
    "Galaxy S30 Plus",
    "Galaxy S30 Ultra",
    "Galaxy S4",
    "Galaxy S4 Mini",
    "Galaxy S5",
    "Galaxy S5 Mini",
    "Galaxy S6",
    "Galaxy S6 Edge",
    "Galaxy S6 Edge Plus",
    "Galaxy S7",
    "Galaxy S7 Edge",
    "Galaxy S72",
    "Galaxy S8",
    "Galaxy S8 Plus",
    "Galaxy S9",
    "Galaxy S9 Plus",
    "Galaxy S9 Pro",
    "Oppo Reno 5 Lite",
    "OPPO A15",
    "OPPO A15S",
    "OPPO A31",
    "OPPO A5 2020",
    "OPPO A52",
    "OPPO A5S",
    "OPPO A73",
    "OPPO A9",
    "OPPO A9 2020",
    "Oppo A1 Pro",
    "Oppo A12",
    "Oppo A16",
    "Oppo A17",
    "Oppo A36",
    "Oppo A5",
    "Oppo A53",
    "Oppo A53 2020",
    "Oppo A53S",
    "Oppo A54",
    "Oppo A54 4G",
    "Oppo A55",
    "Oppo A55 5G",
    "Oppo A57",
    "Oppo A72",
    "Oppo A74",
    "Oppo A7X",
    "Oppo A91",
    "Oppo A92",
    "Oppo A94",
    "Oppo A95",
    "Oppo Reno 2",
    "Oppo Reno 2Z",
    "Oppo Reno 3",
    "Oppo Reno 4",
    "Oppo Reno 4 Lite",
    "Oppo Reno 4 Pro",
    "Oppo Reno 4 Pro 4G",
    "Oppo Reno 4 Pro 5G",
    "Oppo Reno 5",
    "Oppo Reno 5 5G",
    "Oppo Reno 5 Pro",
    "Oppo Reno 5 Pro 5G",
    "Oppo Reno 6",
    "Oppo Reno 6 4G",
    "Oppo Reno Z",
    "Oppo Reno8 5G",
    "Oppo Reno8 Lite",
    "Oppo Reno8 T 4G",
    "Oppo Reno8 T 5G",
    "Oppo Reno9",
    "Redmi 10",
    "Redmi 10 2022",
    "Redmi 10 5G",
    "Redmi 10A",
    "Redmi 10C",
    "Redmi 12C",
    "Redmi 3 Pro",
    "Redmi 4",
    "Redmi 4A",
    "Redmi 4X",
    "Redmi 5",
    "Redmi 5 Plus",
    "Redmi 5A",
    "Redmi 6",
    "Redmi 6 Pro",
    "Redmi 6A",
    "Redmi 7",
    "Redmi 7A",
    "Redmi 8",
    "Redmi 8A",
    "Redmi 8t",
    "Redmi 9",
    "Redmi 9 Prime",
    "Redmi 9 Pro",
    "Redmi 9A",
    "Redmi 9C",
    "Redmi 9T",
    "Redmi 9i Sport",
    "Redmi 9s",
    "Redmi K30",
    "Redmi K30 Pro",
    "Redmi K30S",
    "Redmi K40",
    "Redmi K40 Gaming",
    "Redmi K40 Pro",
    "Redmi K40S",
    "Redmi K50",
    "Redmi K50 Pro",
    "Redmi K60E",
    "Redmi Note 10",
    "Redmi Note 10 5G",
    "Redmi Note 10 Pro",
    "Redmi Note 10 Pro Max",
    "Redmi Note 10T",
    "Redmi Note 10s",
    "Redmi Note 11",
    "Redmi Note 11 5G",
    "Redmi Note 11 Pro",
    "Redmi Note 11 Pro 5G",
    "Redmi Note 11 Pro Plus",
    "Redmi Note 11E",
    "Redmi Note 11S",
    "Redmi Note 11T",
    "Redmi Note 11T 5G",
    "Redmi Note 12",
    "Redmi Note 12 5G",
    "Redmi Note 12 Pro",
    "Redmi Note 12 Pro 5G",
    "Redmi Note 12 Pro+",
    "Redmi Note 7",
    "Redmi Note 7 Pro",
    "Redmi Note 8",
    "Redmi Note 8 Pro",
    "Redmi Note 8T",
    "Redmi Note 9",
    "Redmi Note 9 4G",
    "Redmi Note 9 5G",
    "Redmi Note 9 Pro",
    "Redmi Note 9 Pro 5G",
    "Redmi Note 9 Pro Max",
    "Redmi Note 9S",
    "Redmi Note 9S; Note 9 Pro",
    "Redmi Note 9T",
    "Reno 2",
    "Reno 2Z",
    "Reno 3",
    "Reno 3 Pro",
    "Reno 3 Pro 5G",
    "Reno 4",
    "Reno 4 Lite",
    "Reno 4 Pro",
    "Reno 5",
    "Reno 5 Lite",
    "Reno 5 Pro",
    "Reno 6",
    "Reno 6 Pro",
    "Reno 7",
    "Reno 7 4G",
    "Reno 7 Lite",
    "Reno 7 Lite 5G",
    "Reno 7Z 5G",
    "Reno2 Z",
    "Reno3 Pro",
    "Reno4 Lite",
    "Reno4 Pro",
    "Samsung Galaxy A03S",
    "Samsung Galaxy A04E",
    "Samsung Galaxy A13",
    "Samsung Galaxy A13 4G",
    "Samsung Galaxy A20E",
    "Samsung Galaxy A23",
    "Samsung Galaxy A23/F23",
    "Samsung Galaxy A30 JP",
    "Samsung Galaxy A32 5G",
    "Samsung Galaxy A33 5G",
    "Samsung Galaxy A42",
    "Samsung Galaxy A5 2017",
    "Samsung Galaxy A60",
    "Samsung Galaxy A70S",
    "Samsung Galaxy A8 2016",
    "Samsung Galaxy A80",
    "Samsung Galaxy Ace Plus S7500",
    "Samsung Galaxy Ace S5830",
    "Samsung Galaxy C5",
    "Samsung Galaxy C7 Pro",
    "Samsung Galaxy C9 Pro",
    "Samsung Galaxy Corby 2 S3850",
    "Samsung Galaxy Core 2",
    "Samsung Galaxy Core Prime G360",
    "Samsung Galaxy Core i8260",
    "Samsung Galaxy E250",
    "Samsung Galaxy Gio S5660",
    "Samsung Galaxy Grand 2",
    "Samsung Galaxy Grand Max",
    "Samsung Galaxy J1 2016",
    "Samsung Galaxy J1 Mini",
    "Samsung Galaxy J1 Mini Prime",
    "Samsung Galaxy J3 2017",
    "Samsung Galaxy J330 Pro",
    "Samsung Galaxy J4 Core",
    "Samsung Galaxy J5 2016",
    "Samsung Galaxy J5 2017",
    "Samsung Galaxy J5 Pro",
    "Samsung Galaxy J7 2017",
    "Samsung Galaxy J7 Pro",
    "Samsung Galaxy M10S",
    "Samsung Galaxy M13",
    "Samsung Galaxy M22",
    "Samsung Galaxy M32",
    "Samsung Galaxy M40",
    "Samsung Galaxy M53 5G",
    "Samsung Galaxy Mega",
    "Samsung Galaxy Mini S5570",
    "Samsung Galaxy Note",
    "Samsung Galaxy Note 7",
    "Samsung Galaxy Note Edge",
    "Samsung Galaxy S Advance İ9070",
    "Samsung Galaxy S Duos S7562",
    "Samsung Galaxy S İ9000",
    "Samsung Galaxy S2",
    "Samsung Galaxy S21 FE 5G",
    "Samsung Galaxy S22",
    "Samsung Galaxy S22 Plus",
    "Samsung Galaxy S22 Ultra",
    "Samsung Galaxy S23 Plus",
    "Samsung Galaxy S23 Ultra",
    "Samsung Galaxy S3350",
    "Samsung Galaxy S3600",
    "Samsung Galaxy S4 Zoom",
    "Samsung Galaxy S5230 Star",
    "Samsung Galaxy S7 Edge",
    "Samsung Galaxy S7 Plus",
    "Samsung Galaxy S8",
    "Samsung Galaxy S8 Plus",
    "Samsung Galaxy Wave 2 S8530",
    "Samsung Galaxy Wave S5253",
    "Samsung Galaxy Wave S7233",
    "Samsung Galaxy Wave S8500",
    "Samsung Galaxy Win i8552",
    "Samsung Galaxy Wonder İ8150",
    "Samsung Galaxy Xcover 4",
    "Samsung Galaxy Xcover Pro",
    "Samsung Galaxy Y S5360",
    "Samsung Galaxy Z Flip",
    "Samsung Galaxy Z Fold 2",
    "Samsung Galaxy Z Fold 3",
    "Samsung Galaxy Z Fold3 5G",
    "Tecno Oppo Reno 4 Pro",
    "Xiaomi 11T",
    "Xiaomi 12 Lite",
    "Xiaomi 12T/12T Pro",
    "Xiaomi 13",
    "Xiaomi 13 Lite",
    "Xiaomi 13 Pro",
    "Xiaomi 13 Ultra",
    "Xiaomi Mi 10",
    "Xiaomi Mi 10 5G",
    "Xiaomi Mi 10 Pro",
    "Xiaomi Mi 10 Ultra",
    "Xiaomi Mi 10C",
    "Xiaomi Mi 10T / 10T Pro",
    "Xiaomi Mi 11",
    "Xiaomi Mi 11 Ultra",
    "Xiaomi Mi 11T 5G",
    "Xiaomi Mi 11T Pro 5G",
    "Xiaomi Mi 5s",
    "Xiaomi Mi 5s Plus",
    "Xiaomi Mi 5x",
    "Xiaomi Mi 6X",
    "Xiaomi Mi 8 Pro",
    "Xiaomi Mi 9 Se",
    "Xiaomi Mi A3",
    "Xiaomi Mi Max",
    "Xiaomi Mi Max 2",
    "Xiaomi Mi Max 3",
    "Xiaomi Mi Mix",
    "Xiaomi Mi Mix 2",
    "Xiaomi Mi Mix 2S",
    "Xiaomi Mi Mix 4",
    "Xiaomi Mi Note 10 Pro",
    "Xiaomi Mi Note 11S",
    "Xiaomi Mi Note 2",
    "Xiaomi Mi Pad 5",
    "Xiaomi Mİ 4C",
    "Xiaomi Note 8 Pro",
    "Xiaomi Poco C40",
    "Xiaomi Poco M3",
    "Xiaomi Poco M3 Pro",
    "Xiaomi Poco M4 Pro 5G",
    "Xiaomi Poco X3 GT",
    "Xiaomi Red Mi 10 Prime+ 5G/Red Mi Note 11E",
    "Xiaomi Red Mi 10A",
    "Xiaomi Red Mi 10C 4G Global",
    "Xiaomi Red Mi K30",
    "Xiaomi Red Mi K40S",
    "Xiaomi Red Mi Note 11 4G / Note 11S",
    "Xiaomi Red Mi Note 8",
    "Xiaomi Red Mi Note 9 Pro",
    "Xiaomi Red Mi Note 9 Pro 5G",
    "Xiaomi Red Mi Note 9 Pro Max",
    "Xiaomi Redmi 10",
    "Xiaomi Redmi 12C",
    "Xiaomi Redmi 3 Pro",
    "Xiaomi Redmi 3s",
    "Xiaomi Redmi 4",
    "Xiaomi Redmi 4A",
    "Xiaomi Redmi 4x",
    "Xiaomi Redmi 5",
    "Xiaomi Redmi 5A",
    "Xiaomi Redmi Go",
    "Xiaomi Redmi K20",
    "Xiaomi Redmi Note 10 5G",
    "Xiaomi Redmi Note 11",
    "Xiaomi Redmi Note 11 Pro",
    "Xiaomi Redmi Note 11T Pro+ 5G",
    "Xiaomi Redmi Note 12",
    "Xiaomi Redmi Note 12 4G",
    "Xiaomi Redmi Note 4x",
    "Xiaomi Redmi Pro",
    "Xiaomi Redmi Y1 Lite",
    "iPhone",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone 12",
    "iPhone 12 Max",
    "iPhone 12 Mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro Mini",
    "iPhone 13",
    "iPhone 13 Mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 4",
    "iPhone 4S",
    "iPhone 5",
    "iPhone 5 / 5s",
    "iPhone 5 5S",
    "iPhone 5S",
    "iPhone 6",
    "iPhone 6 / 6S",
    "iPhone 6 Plus",
    "iPhone 6 Plus - 6S Plus",
    "iPhone 6 Plus / 6S Plus",
    "iPhone 6/ 6S",
    "iPhone 6/6S",
    "iPhone 6Plus/ 7Plus/ 8Plus",
    "iPhone 6S",
    "iPhone 6S Plus",
    "iPhone 7",
    "iPhone 7 / 8",
    "iPhone 7 Plus",
    "iPhone 7/8",
    "iPhone 7/8 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone Max",
    "iPhone SE",
    "iPhone SE 2",
    "iPhone SE 2020",
    "iPhone SE 2022",
    "iPhone SE 3 2022",
    "iPhone X",
    "iPhone X / XS",
    "iPhone X/XS",
    "iPhone XR",
    "iPhone XR 6.1",
    "iPhone XS",
    "iPhone XS MaiPhone X",
    "iPhone XS Max",
    "iPhone XS Max 6.5",
    "iphone",
];
999;
var colors = [
    "Altın",
    "--",
    "41S-Sarı",
    "50P-Pembe",
    "Abanoz",
    "Ahşap",
    "Ahşap Rengi",
    "Alp Yeşili",
    "Altın",
    "Altın - Beyaz",
    "Altın - Gri",
    "Altın - Gül",
    "Altın - Gümüş",
    "Altın - Koyu Pembe",
    "Altın - Kırmızı",
    "Altın - Lila",
    "Altın - Mavi",
    "Altın - Pembe",
    "Altın - Sarı",
    "Altın - Siyah",
    "Altın - Yeşil",
    "Altın Dore",
    "Altın Pembe",
    "Antik Beyaz",
    "Antrasit",
    "Antrasit - Gri",
    "Asker Yeşili",
    "Askeri Kamuflaj",
    "Azure",
    "Açık Bej",
    "Açık Bordo",
    "Açık Cam Göbeği",
    "Açık Gri",
    "Açık Gümüş",
    "Açık Kahverengi",
    "Açık Kahverengi - Siyah",
    "Açık Kahverengi - Yeşil",
    "Açık Kırmızı",
    "Açık Lacivert",
    "Açık Lila",
    "Açık Mavi",
    "Açık Mavi - Kırmızı",
    "Açık Mavi - Lacivert",
    "Açık Mavi - Mavi",
    "Açık Mavi - Mor",
    "Açık Mavi - Rose",
    "Açık Mor",
    "Açık Mor - Mor",
    "Açık Mor - Pembe",
    "Açık Mor - Siyah",
    "Açık Mor - Yeşil",
    "Açık Mürdüm",
    "Açık Pembe",
    "Açık Pembe - Beyaz",
    "Açık Pembe - Koyu Yeşil",
    "Açık Pembe - Yeşil",
    "Açık Sarı",
    "Açık Siyah",
    "Açık Turkuaz",
    "Açık Turuncu",
    "Açık Vişne",
    "Açık Yeşil",
    "Açık Yeşil - Mor",
    "Açık Yeşil - Siyah",
    "Açık Yeşil - Turuncu",
    "Açık Yeşil - Yeşil",
    "Açık Yeşil Kamuflaj",
    "Bakır",
    "Bal Rengi",
    "Baltık Mavisi",
    "Bebek Mavisi",
    "Bej",
    "Bej - Gri",
    "Bej - Mavi",
    "Bej - Pembe",
    "Bej - Sarı",
    "Beril",
    "Berry",
    "Beyaz",
    "Beyaz - Altın - Siyah",
    "Beyaz - Fuşya",
    "Beyaz - Gri",
    "Beyaz - Gümüş",
    "Beyaz - Kahverengi",
    "Beyaz - Kırmızı",
    "Beyaz - Kırmızı - Siyah",
    "Beyaz - Lacivert",
    "Beyaz - Mavi",
    "Beyaz - Mavi - Altın",
    "Beyaz - Mavi - Siyah",
    "Beyaz - Mor",
    "Beyaz - Mor - Siyah",
    "Beyaz - Pembe",
    "Beyaz - Sarı",
    "Beyaz - Siyah",
    "Beyaz - Taba",
    "Beyaz - Turkuaz - Fuşya",
    "Beyaz - Turuncu",
    "Beyaz - Yeşil",
    "Beyaz Ahşap",
    "Beyaz Karbon",
    "Beyaz-Turuncu",
    "Beyaz-Yeşil",
    "Black",
    "BlackBerry",
    "Blue",
    "Blue Cobalt",
    "Blush Gold",
    "Bodro",
    "Bordo",
    "Bordo - Siyah",
    "Bronz",
    "Bronz - Altın",
    "Bronz - Gümüş",
    "Brown",
    "Buz Mavisi",
    "Buzlu Beyaz",
    "Buzlu Mavi",
    "Buzlu Siyah",
    "Buzlu Şeffaf",
    "CS Siyah",
    "Calypso Blue",
    "Cam",
    "Cam Göbeği",
    "Camel",
    "Cat",
    "Champagne Gold",
    "Charcoal Black",
    "Ciassic Siyah",
    "Clear",
    "Cocoa",
    "Copper Gold",
    "Crystal Clear",
    "Dallar",
    "Dark Olive",
    "Dark Silver",
    "Dark yeşil",
    "Darling Pink",
    "Deep Blue",
    "Deniz Kabuğu",
    "Deniz Mavisi",
    "Deniz Mavisi - Gri",
    "Deniz Yıldızı",
    "Deri",
    "Derin Mavi",
    "Derin Mor",
    "Desenli",
    "Duman Gri",
    "Edge Glow Pink",
    "Eflatun",
    "Eflatun - Mavi",
    "Ekru",
    "Ekru - Mor",
    "Ekru - Pembe",
    "Elegant Yeşil",
    "Erik Çiçeği Rengi",
    "Eski Harita Eyfel",
    "Eyfel Kule",
    "Flamingo",
    "Fosfor Sarı",
    "Fosfor Yeşili",
    "Fosforlu Yeşil - Siyah",
    "Fuşya",
    "Füme",
    "Füme - Pembe",
    "Fıstık Yeşili",
    "Gece Mavisi",
    "Gece Siyahı",
    "Gece Yeşili",
    "Gerbera Pembesi",
    "Glossy Finish Blue",
    "Glossy Finish Clear",
    "Glossy Finish Purple",
    "Glossy Finish Red",
    "Gold",
    "Gold - Koyu Pembe",
    "Gold - Kırmızı",
    "Gold-Siyah",
    "Gold1",
    "Gray",
    "Gri",
    "Gri - Altın",
    "Gri - Açık Mavi",
    "Gri - Beyaz",
    "Gri - Fuşya",
    "Gri - Gold",
    "Gri - Kahverengi",
    "Gri - Kırmızı",
    "Gri - Mavi",
    "Gri - Pembe",
    "Gri - Pembe sistemde tanımlı bir ürün tipi değeri değildir.",
    "Gri - Pudra",
    "Gri - Pudra sistemde tanımlı bir ürün tipi değeri değildir.",
    "Gri - Rose - Altın",
    "Gri - Rose Gold",
    "Gri - Siyah",
    "Gri - Turkuaz",
    "Gri - Yeşil",
    "Gri - Yeşil - Pembe",
    "Gri Kamuflaj",
    "Gri-Lacivert",
    "Gri-Siyah",
    "Gunmetal",
    "Gök Mavisi",
    "Gök Mavisi - Mor",
    "Gökkuşağı",
    "Gökyüzü Mavisi",
    "Gökyüzü Mavisi - Mor",
    "Göl Mavi",
    "Göl Mavisi",
    "Göl Yeşili",
    "Gül Kurusu",
    "Gül Pembesi",
    "Gül Rengi",
    "Gümüş",
    "Gümüş - Altın",
    "Gümüş - Beyaz",
    "Gümüş - Gri",
    "Gümüş - Kırmızı",
    "Gümüş - Mavi",
    "Gümüş - Pembe",
    "Gümüş - Sarı",
    "Gümüş - Siyah",
    "Gümüş - Yeşil",
    "Gümüş Gri",
    "Gümüş Rose Gold",
    "Gümüş Rose Siyah",
    "Gümüş-Siyah",
    "Hafif Siyah",
    "Haki",
    "Haki - Sarı",
    "Haki - Siyah",
    "Haki Yeşil",
    "Hardal",
    "Hava Mavisi",
    "Hot Lips Pink",
    "Hot Pink",
    "Jean Blue",
    "Jean Mavi",
    "Jelly Beyaz",
    "Jelly Gri",
    "Jelly Kahverengi",
    "Jelly Mavi",
    "Jelly Pembe",
    "Jelly Siyah",
    "Jelly Turuncu",
    "Jelly Yeşil",
    "Kahve",
    "Kahverengi",
    "Kahverengi - Altın",
    "Kahverengi - Beyaz",
    "Kahverengi - Gri",
    "Kahverengi - Kırmızı",
    "Kahverengi - Sarı",
    "Kahverengi - Siyah",
    "Kahverengi - Turuncu",
    "Kahverengi - Yeşil",
    "Kalp",
    "Kamelya",
    "Kamuflaj",
    "Kavuniçi",
    "Kayısı Rengi",
    "Kemik",
    "Kiraz Çiçeği",
    "Kiremit",
    "Kiss Red",
    "Klasik Kahve",
    "Klasik Kahverengi",
    "Klop Black",
    "Klop Brown",
    "Koyu Bej",
    "Koyu Füme",
    "Koyu Gold",
    "Koyu Gri",
    "Koyu Gri - Sarı",
    "Koyu Gri - Siyah",
    "Koyu Gümüş",
    "Koyu Kahve",
    "Koyu Kahverengi",
    "Koyu Kahverengi - Altın",
    "Koyu Kahverengi - Sarı",
    "Koyu Kırmızı",
    "Koyu Kızıl",
    "Koyu Lacivert",
    "Koyu Lila",
    "Koyu Mavi",
    "Koyu Mavi - Gümüş",
    "Koyu Mavi - Koyu Pembe",
    "Koyu Mavi - Mor",
    "Koyu Mavi - Siyah",
    "Koyu Mor",
    "Koyu Pembe",
    "Koyu Pembe - Altın",
    "Koyu Pembe - Açık Mavi",
    "Koyu Pembe - Koyu Mavi",
    "Koyu Pembe - Mavi",
    "Koyu Pembe - Mor",
    "Koyu Pembe - Siyah",
    "Koyu Sarı",
    "Koyu Siyah",
    "Koyu Turkuaz",
    "Koyu Turuncu",
    "Koyu Yeşil",
    "Koyu Yeşil - Kırmızı",
    "Koyu Yeşil - Siyah",
    "Kraliyet Mavisi",
    "Krem",
    "Krem - Sarı",
    "Krem - Siyah",
    "Krem Ahşap",
    "Krem Rengi",
    "Kristal Mavi",
    "Krom",
    "Kulübe",
    "Kum Pembe",
    "Kumral",
    "Kuşlu",
    "Köknar Yeşili",
    "Kömür",
    "Kömür Grisi",
    "Kömür Rengi",
    "Körfez Mavisi",
    "Kül Gri",
    "Kül Rengi",
    "Kırmızı",
    "Kırmızı - Açık Gri",
    "Kırmızı - Bej",
    "Kırmızı - Beyaz",
    "Kırmızı - Gri",
    "Kırmızı - Gül Rengi",
    "Kırmızı - Gümüş",
    "Kırmızı - Haki",
    "Kırmızı - Kahverengi",
    "Kırmızı - Kırmızı",
    "Kırmızı - Lacivert",
    "Kırmızı - Mavi",
    "Kırmızı - Mor",
    "Kırmızı - Pembe",
    "Kırmızı - Rose Gold",
    "Kırmızı - Sarı",
    "Kırmızı - Siyah",
    "Kırmızı - Turkuaz",
    "Kırmızı - Turuncu",
    "Kırmızı - Yeşil",
    "Kırmızı - Şeffaf",
    "Kırmızı Kamuflaj",
    "Kırmızı1",
    "Kırık Beyaz",
    "Kızıl",
    "Lacivert",
    "Lacivert - Altın",
    "Lacivert - Bordo",
    "Lacivert - Gri",
    "Lacivert - Kahverengi",
    "Lacivert - Koyu Yeşil",
    "Lacivert - Krem",
    "Lacivert - Kırmızı",
    "Lacivert - Mavi",
    "Lacivert - Mavi sistemde tanımlı bir ürün tipi değeri değildir.",
    "Lacivert - Mor",
    "Lacivert - Pembe",
    "Lacivert - Pembe sistemde tanımlı bir ürün tipi değeri değildir.",
    "Lacivert - Pudra",
    "Lacivert - Pudra sistemde tanımlı bir ürün tipi değeri değildir.",
    "Lacivert - Sarı",
    "Lacivert - Siyah",
    "Lacivert - Yeşil",
    "Lacivert-Siyah",
    "Lavanta",
    "Lavanta Grisi",
    "Lavender Purple",
    "Leopar",
    "Leylak",
    "Leylak Moru",
    "Light Silver",
    "Lila",
    "Lila - Açık Mavi",
    "Lila - Bej",
    "Lila - Beyaz",
    "Lila - Beyaz - Kırmızı",
    "Lila - Kırmızı",
    "Lila - Mavi",
    "Lila - Mavi - Beyaz",
    "Lila - Mavi - Kırmızı",
    "Lila - Mor",
    "Lila - Pembe",
    "Lila - Siyah",
    "Lila - Turuncu",
    "Limon Sarısı",
    "Limon Yeşili",
    "Marine Green",
    "Mat",
    "Mat Beyaz",
    "Mat Sarı",
    "Mat Siyah",
    "Mat Turuncu",
    "Mat Şeffaf",
    "Matcha Yeşili",
    "Matte Finish Black",
    "Mavi",
    "Mavi - Altın",
    "Mavi - Beyaz",
    "Mavi - Fuşya",
    "Mavi - Füme",
    "Mavi - Gold",
    "Mavi - Gri",
    "Mavi - Gök Mavisi",
    "Mavi - Gül",
    "Mavi - Gümüş",
    "Mavi - Haki",
    "Mavi - Kahverengi",
    "Mavi - Koyu Pembe",
    "Mavi - Krem",
    "Mavi - Kırmızı",
    "Mavi - Mavi",
    "Mavi - Mor",
    "Mavi - Pembe",
    "Mavi - Rose",
    "Mavi - Sarı",
    "Mavi - Siyah",
    "Mavi - Turuncu",
    "Mavi - Yeşil",
    "Mavi - Şeffaf",
    "Mavi Kamuflaj",
    "Mavi-Pembe",
    "Menekşe",
    "Mercan",
    "Metal",
    "Metalik Altın",
    "Metalik Gümüş",
    "Metalik Koyu Mavi",
    "Metalik Kırmızı",
    "Metalik Lacivert",
    "Metalik Mavi",
    "Metalik Mor",
    "Metalik Sarı",
    "Metalik Siyah",
    "Metalik Yeşil",
    "Midnight Blue",
    "Mint",
    "Mint Yeşili",
    "Mint Yeşili - Kırmızı",
    "Monaco Blue",
    "Mor",
    "Mor - Altın",
    "Mor - Açık Pembe",
    "Mor - Açık Yeşil",
    "Mor - Bej",
    "Mor - Beyaz",
    "Mor - Gri",
    "Mor - Gül",
    "Mor - Gümüş",
    "Mor - Koyu Mavi",
    "Mor - Kırmızı",
    "Mor - Lacivert",
    "Mor - Mavi",
    "Mor - Mavi - Kırmızı",
    "Mor - Pembe",
    "Mor - Pembe - Beyaz",
    "Mor - Rose",
    "Mor - Sarı",
    "Mor - Siyah",
    "Mor - Turkuaz",
    "Mor - Turuncu",
    "Mor - Yeşil",
    "Mor - Yeşil - Turuncu",
    "Mor1",
    "Mykonos Blue",
    "Mürdüm",
    "Nane Yeşil - Beyaz",
    "Nane Yeşil - Mor",
    "Nane Yeşili",
    "Nar",
    "Nar Çiçeği",
    "Nefti Yeşil",
    "Neon Absinthe Green",
    "Neon Calypso Blue",
    "Neon Hot Lips Pink",
    "Neon Kırmızı",
    "Neon Lightning Yellow",
    "Neon Menekşe",
    "Neon Orchid Purple",
    "Neon Pembe",
    "Neon Sarı",
    "Neon Sunrise Pink",
    "Neon Turuncu",
    "Newyork Taksi",
    "Nickel Grey",
    "Nokia",
    "Ocean Blue",
    "Okyanus Mavisi",
    "Orchid Purple",
    "Ordu Yeşili",
    "Ordu Yeşili - Turuncu",
    "Orman Yeşili",
    "Papatya",
    "Paris",
    "Parlak Gümüş",
    "Parlak Sarı",
    "Parlak Siyah",
    "Parlak Şeffaf",
    "Parlament Mavi",
    "Pastel Kırmızı",
    "Pastel Pembe",
    "Pastel Sarı",
    "Pastel Yeşil",
    "Pebble",
    "Pembe",
    "Pembe - Altın",
    "Pembe - Açık Mavi",
    "Pembe - Açık Mor",
    "Pembe - Açık Yeşil",
    "Pembe - Bej",
    "Pembe - Beyaz",
    "Pembe - Beyaz - Mor",
    "Pembe - Fuşya",
    "Pembe - Gri",
    "Pembe - Gök Mavisi",
    "Pembe - Gökyüzü Mavisi",
    "Pembe - Gül",
    "Pembe - Gümüş",
    "Pembe - Kahverengi",
    "Pembe - Koyu Kırmızı",
    "Pembe - Kırmızı",
    "Pembe - Lacivert",
    "Pembe - Lila",
    "Pembe - Mavi",
    "Pembe - Mor",
    "Pembe - Mor - Altın",
    "Pembe - Sarı",
    "Pembe - Siyah",
    "Pembe - Turkuaz",
    "Pembe - Turuncu",
    "Pembe - Yeşil",
    "Pembe - Şarap Kırmızısı",
    "Pembe - Şeffaf",
    "Pembe Neon",
    "Pembe-Siyah",
    "Pembe-Yeşil",
    "Petrol",
    "Petrol Mavisi",
    "Petrol Yeşili",
    "Petrol Yeşili - Altın",
    "Pink Sand",
    "Platin Gri - Altın",
    "Platin Gri - Gümüş",
    "Portakal",
    "Pudra",
    "Pudra Pembe",
    "Red",
    "Renkli",
    "Renksiz",
    "Retro Yeşil",
    "Rose",
    "Rose - Açık Mavi",
    "Rose - Gold",
    "Rose - Kırmızı",
    "Rose - Mavi",
    "Rose - Mor",
    "Rose - Sarı",
    "Rose - Siyah",
    "Rose Crystal",
    "Rose Gold",
    "Rose Gold - Pembe",
    "Rose Gold-Siyah",
    "Rose Gri",
    "Rose Pembe",
    "Rose Red",
    "Rose Siyah",
    "Royal Mavi",
    "Rugged Armor",
    "S Şeffaf",
    "Sade",
    "Safir",
    "Safir Mavisi",
    "Safir Mavisi - Siyah",
    "Saks",
    "Saks Mavi",
    "Sap Yeşili",
    "Sapphire",
    "Sarı",
    "Sarı - Beyaz",
    "Sarı - Kahverengi",
    "Sarı - Kırmızı",
    "Sarı - Lacivert",
    "Sarı - Lila",
    "Sarı - Mavi",
    "Sarı - Mor",
    "Sarı - Mor - kırmızı",
    "Sarı - Pembe",
    "Sarı - Siyah",
    "Sarı - Turuncu",
    "Sarı - Yeşil",
    "Sarı 319850",
    "Saydam",
    "Sea Blue",
    "Seffaf Beyaz",
    "Shine Gold",
    "Sierra Mavisi",
    "Silver",
    "Simli",
    "Simli Şeffaf",
    "Siyah",
    "Siyah - Altın",
    "Siyah - Açık Kırmızı",
    "Siyah - Açık Mavi",
    "Siyah - Beyaz",
    "Siyah - Beyaz - Gri",
    "Siyah - Bordo",
    "Siyah - Fuşya",
    "Siyah - Gold",
    "Siyah - Gri",
    "Siyah - Gül",
    "Siyah - Gümüş",
    "Siyah - Kahverengi",
    "Siyah - Koyu Kırmızı",
    "Siyah - Koyu Mavi",
    "Siyah - Koyu Yeşil",
    "Siyah - Kırmızı",
    "Siyah - Lacivert",
    "Siyah - Mavi",
    "Siyah - Mor",
    "Siyah - Pembe",
    "Siyah - Pembe - Altın",
    "Siyah - Rose",
    "Siyah - Rose - Altın",
    "Siyah - Rose Gold",
    "Siyah - Rosegold",
    "Siyah - Sarı",
    "Siyah - Silver",
    "Siyah - Siyah",
    "Siyah - Turkuaz",
    "Siyah - Turkuvaz",
    "Siyah - Turuncu",
    "Siyah - Yeşil",
    "Siyah - Şarap Kırmızısı",
    "Siyah - Şeffaf",
    "Siyah Büyük Pencere",
    "Siyah Gri",
    "Siyah Hası",
    "Siyah Kamuflaj",
    "Siyah Karbon",
    "Siyah Kömür",
    "Siyah Melanj",
    "Siyah Mermer",
    "Siyah-Pembe",
    "Somon",
    "Somon Rengi",
    "Stand Black",
    "Stand Gold",
    "Stand Rose",
    "Stand White",
    "Steel Silver",
    "Stone",
    "Su Yeşili",
    "Sıcak Pembe",
    "TAN",
    "Taba",
    "Taba - Siyah",
    "Taksim Tramvay",
    "Taupe",
    "Taş",
    "Taş - Beyaz",
    "Tekne",
    "Telefon Kulübesi",
    "Tennis Ball Green",
    "Ticket",
    "Titanium",
    "Titanyum",
    "Titanyum Gri",
    "Totem",
    "Toz Pembe",
    "Transparan",
    "Turkuaz",
    "Turkuaz - Beyaz",
    "Turkuaz - Beyaz - Açık Pembe",
    "Turkuaz - Beyaz - Yeşil",
    "Turkuaz - Fuşya",
    "Turkuaz - Gri",
    "Turkuaz - Kırmızı",
    "Turkuaz - Pembe",
    "Turkuaz - Turuncu",
    "Turkuvaz",
    "Turkuvaz - Mavi",
    "Turuncu",
    "Turuncu - Bej",
    "Turuncu - Beyaz",
    "Turuncu - Beyaz - Yeşil",
    "Turuncu - Gri",
    "Turuncu - Kırmızı",
    "Turuncu - Lacivert",
    "Turuncu - Mavi",
    "Turuncu - Mor",
    "Turuncu - Sarı",
    "Turuncu - Siyah",
    "Turuncu - Turkuaz - Mavi",
    "Turuncu - Yeşil",
    "Turuncu Kamuflaj",
    "Ultra Crystal",
    "Ultra Violet",
    "Uzay Grisi",
    "Violet",
    "Vizon",
    "Vişne Çürüğü",
    "White",
    "Wild Salmon Pink",
    "Wine",
    "Yavruağzı",
    "Yelkenli",
    "Yeşil",
    "Yeşil - Altın",
    "Yeşil - Bej",
    "Yeşil - Beyaz",
    "Yeşil - Gri",
    "Yeşil - Gümüş",
    "Yeşil - Haki",
    "Yeşil - Koyu Gri",
    "Yeşil - Koyu Yeşil",
    "Yeşil - Kırmızı",
    "Yeşil - Lacivert",
    "Yeşil - Mavi",
    "Yeşil - Mavi - Mor",
    "Yeşil - Mercan",
    "Yeşil - Mor",
    "Yeşil - Pembe",
    "Yeşil - Sarı",
    "Yeşil - Siyah",
    "Yeşil - Ten Rengi",
    "Yeşil - Turkuaz",
    "Yeşil - Turuncu",
    "Yeşil - Turuncu - Mor",
    "Yeşil - Şeffaf",
    "Yeşil Kamuflaj",
    "Zebra",
    "Zeytin Yeşili",
    "iPhone",
    "Çam Yeşili",
    "Çay",
    "Çim Yeşili",
    "Çimen Yeşili",
    "Çizgili",
    "Çizgili Deri",
    "Çiçek",
    "Çiçek Desenli",
    "Çiçek-Kuş",
    "Çok Renkli",
    "Çubuk Adam",
    "İnci Beyazı",
    "İstanbul",
    "Şafak Mavisi",
    "Şampanya",
    "Şampanya - Altın",
    "Şarap Kırmızısı",
    "Şeffaf",
    "Şeffaf - Altın",
    "Şeffaf - Beyaz",
    "Şeffaf - Füme",
    "Şeffaf - Gold",
    "Şeffaf - Gri",
    "Şeffaf - Gümüş",
    "Şeffaf - Kırmızı",
    "Şeffaf - Lacivert",
    "Şeffaf - Lila",
    "Şeffaf - Mavi",
    "Şeffaf - Mor",
    "Şeffaf - Pembe",
    "Şeffaf - Rose Gold",
    "Şeffaf - Sarı",
    "Şeffaf - Siyah",
    "Şeffaf - Turkuaz",
    "Şeffaf - Turuncu",
    "Şeffaf - Yeşil",
    "Şeffaf Beyaz",
    "Şeffaf Bronz",
    "Şeffaf Gold",
    "Şeffaf Gri",
    "Şeffaf Gül",
    "Şeffaf Kırmızı",
    "Şeffaf Mat",
    "Şeffaf Mavi",
    "Şeffaf Mor",
    "Şeffaf Pembe",
    "Şeffaf Sarı",
    "Şeffaf Siyah",
    "Şeffaf Yeşil",
    "Şeftali",
    "Şeker Pembe",
    "Şeker Pembesi",
];
var caseBrands = [
    "Apple",
    "General Mobile",
    "Huawei",
    "Infinix",
    "Omix",
    "Oppo",
    "Poco",
    "Realme",
    "Redmi",
    "Reeder",
    "Samsung",
    "Tecno",
    "iPhone",
];
var guaranteesType = [
    "İthalatçı Garantili",
    "Sony Eurasia Garantili",
];
var waterProof = ["Var, Yok"];
// Questions collection
var promptQuestions = [
    {
        type: "input",
        name: "title",
        message: "Ürün adı yazınız",
        filter: function (input, answer) {
            return capitalizeLetters(cleanUp(input));
        },
        validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "input",
        name: "phoneType",
        message: "Telefonun bilinen adı yazınız",
        filter: function (input) {
            return cleanUp(input, false);
        },
        validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "search-checkbox",
        name: "phonesList",
        message: "Telefon modelleri seçiniz",
        choices: phones,
        validate: lengthValidator,
        suffix: ":",
    },
    // {
    //   type: "search-checkbox",
    //   name: "phoneBrandCrap",
    //   message: "phoneBrandCrap seçiniz",
    //   choices: crap,
    //   suffix: ":",
    // },
    {
        type: "input",
        name: "options",
        message: "Seçenekler yazınız (aralarında virgül koyarak)",
        filter: function (input, answer) {
            return cleanUp(input)
                .split(",")
                .map(function (option) {
                // return removeWhiteSpaces(upperLetters(phoneAnswer));
                return capitalizeLetters(option);
            });
        },
        suffix: ":",
    },
    {
        type: "input",
        name: "mainModalCode",
        message: "Ana model kodu yazınız",
        filter: function (input) {
            return cleanUp(input).toUpperCase();
        },
        validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "input",
        name: "brand",
        message: "Marka adı yazınız",
        // validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "search-checkbox",
        name: "colors",
        message: "Renkleri seçiniz",
        choices: colors,
        validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "input",
        name: "price",
        message: "Satış fiyatı yazınız",
        validate: numberValidator,
        suffix: ":",
    },
    {
        type: "input",
        name: "stock",
        message: "Stock adedi yazınız",
        validate: numberValidator,
        suffix: ":",
    },
    {
        type: "input",
        name: "description",
        message: "Ürün açıklaması yazınız",
        validate: lengthValidator,
        suffix: ":",
    },
    {
        type: "search-list",
        name: "material",
        message: "Materyal seçiniz",
        choices: materials,
        suffix: ":",
    },
    {
        type: "search-list",
        name: "caseType",
        message: "Kılıf modeli seçiniz",
        choices: casesTypes,
        suffix: ":",
    },
    {
        type: "search-list",
        name: "caseBrand",
        message: "Uyumlu marka seçiniz",
        choices: caseBrands,
        suffix: ":",
    },
    {
        type: "input",
        name: "path",
        message: "Path?",
        validate: lengthValidator,
        suffix: ":",
    },
];
function main() {
    return __awaiter(this, void 0, void 0, function () {
        var res, result;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, (0, inquirer_1.prompt)(promptQuestions)
                        .then(function (answers) {
                        return answers;
                    })
                        .catch(function (error) {
                        if (error.isTtyError) {
                            // Prompt couldn't be rendered in the current environment
                        }
                        else {
                            // Something else went wrong
                        }
                    })];
                case 1:
                    res = _a.sent();
                    result = res;
                    compile(result);
                    return [2 /*return*/];
            }
        });
    });
}
main();
// - Helpers
/**
 * Trims extra whitespace and lowercases the text
 * @param text The text.
 * @param lowerCase Option to lowerCase the text. Defaults to true.
 * @returns Cleared up text.
 * @example cleanUp("   Text HERE ")
 */
function cleanUp(text, lowerCase) {
    if (lowerCase === void 0) { lowerCase = true; }
    var res = text.trim().replace(/\s+/g, " ");
    return lowerCase ? res.toLowerCase() : res;
}
/**
 * Trims extra whitespace, split it and uppercase first letter then it joins to create a string.
 *
 * @param text The text.
 * @returns Capitalized text.
 */
function capitalizeLetters(text) {
    return text
        .toLowerCase()
        .trim()
        .split(" ")
        .map(function (word) { return "".concat(word.charAt(0).toUpperCase()).concat(word.slice(1)); })
        .join(" ");
}
/**
 * Removes all whitespace.
 *
 * @param text The text.
 * @returns Text without any whitespace.
 */
function removeWhiteSpaces(text) {
    return text.replace(/\s/g, "");
}
/**
 * Generates random number.
 * @param length The length of the generated number.
 * @returns Random set of numbers.
 */
function digitGen(length) {
    var digit = "";
    for (var index = 0; index < length; index++) {
        digit += Math.round(Math.random() * 9);
    }
    return digit;
}
/**
 * It validates the string or the array. It checks if the length is bigger than zero. Since split returns [''], we need to check multiple times for the Array
 * @param text The text.
 * @returns
 */
function lengthValidator(text) {
    if (Array.isArray(text))
        return text.length > 0 && text[0].length > 0 ? true : false;
    if (text.trim().length <= 0)
        return false;
    return true;
}
function numberValidator(value) {
    return !isNaN(parseInt(value)) && lengthValidator(value);
}
function compile(_a) {
    var brand = _a.brand, caseBrand = _a.caseBrand, caseType = _a.caseType, colors = _a.colors, productDescription = _a.productDescription, mainModalCode = _a.mainModalCode, material = _a.material, phoneType = _a.phoneType, phonesList = _a.phonesList, price = _a.price, stockAmount = _a.stockAmount, title = _a.title, path = _a.path, options = _a.options, phoneBrandCrap = _a.phoneBrandCrap;
    var res = [];
    for (var i = 0; i < phonesList.length; i++) {
        // Example: Iphone 11 Pro (from Excel Sheet)
        var phoneName = phonesList[i];
        // TODO: I can have an option to write how many words is it. For example: Samsung Galaxy (2), iPhone (1), Xiaomi Redmi (2)
        // - This doesn't work on 2 words brand
        // const phoneCode = capitalizeLetters(
        //   phonesList[i].split(" ").slice(1).join(" ")
        // );
        // - This works only if I wrote the phoneType the same as the phone brand written in the file
        // TODO: if the phoneType is 2 words, match for each one. For example: Samsung Galaxy, regex for both individually because sometimes the name is Galaxy without the samsung
        var regex = new RegExp(replaceTurkishI(phoneType).toLowerCase(), "gi");
        // Example: 11 Pro
        var phoneNameWithoutBrand = capitalizeLetters(cleanUp(replaceTurkishI(phoneName).toLowerCase().replace(regex, ""), false));
        // Example: 11Pro
        var phoneCode = removeWhiteSpaces(phoneNameWithoutBrand);
        // Example: iPhone 11 Pro Uyumlu I Love Your Mom
        var productTitle = "".concat(phoneType, " ").concat(phoneNameWithoutBrand, " Uyumlu ").concat(title);
        // Example: SB-11Pro
        var productModal = "".concat(mainModalCode, "-").concat(phoneCode);
        // Example: 691
        var randomDigits = digitGen(3);
        for (var j = 0; j < colors.length; j++) {
            // Example: Kırmızı
            var color = colors[j];
            // Example: SuarSB-11ProSari-691
            var barcode = "".concat(capitalizeLetters(brand !== null && brand !== void 0 ? brand : "")).concat(productModal).concat(removeWhiteSpaces(color), "-").concat(randomDigits);
            // Example: SB-11Pro-Siyah
            var iHateHepsiburada = "".concat(productModal, "-").concat(color);
            for (var x = 0; x < options.length; x++) {
                var option = options[x];
                // Fields
                var fields_1 = {
                    "Ürün Adı": productTitle,
                    "Satıcı Stok Kodu": iHateHepsiburada,
                    Barkod: barcode,
                    "Varyant Grup Id": productModal,
                    "Ürün Açıklaması": productDescription,
                    Marka: brand !== null && brand !== void 0 ? brand : "",
                    Desi: 1,
                    KDV: KDV[3],
                    "Garanti Süresi (Ay)": 0,
                    Görsel1: "",
                    Görsel2: "",
                    Görsel3: "",
                    Görsel4: "",
                    Görsel5: "",
                    Fiyat: price,
                    Stok: stockAmount,
                    Video: "",
                    "Uyumlu Model": "",
                    Renk: color,
                    Seçenek: option,
                    "Telefon Modeli": phoneName,
                    "Uyumlu Marka": caseBrand,
                    "Garanti Tipi": "",
                    "Su Geçirmezlik": "",
                    "Ürün  Kodu": "",
                    "Malzeme Türü": material,
                    "Garanti Tipi2": "",
                    "Kılıf Tipi": caseType,
                };
                // Push to the array
                res.push(fields_1);
            }
        }
    }
    writeToExcel(res, cleanUp(path, false).replace(/"/gi, ""), mainModalCode);
}
function replaceTurkishI(text) {
    return text.replace(/i̇/gi, "i").replace(/İ/gi, "I");
}
var XLSX = require("xlsx");
// TODO: Don't override props. Just append to them. (for now it works but not in the way that I want. It should not replace props it should append rows only.)
// TODO: Create a file
function writeToExcel(resultArray, path, mainModalCode) {
    var _a;
    var sheetName = "Kılıflar";
    // Read the file into memory
    var workbook = XLSX.readFile("./hepsiburada.xlsx");
    var worksheets = {};
    for (var _i = 0, _b = workbook.SheetNames; _i < _b.length; _i++) {
        var sheetName_1 = _b[_i];
        // Some helper functions in XLSX.utils generate different views of the sheets:
        //     XLSX.utils.sheet_to_csv generates CSV
        //     XLSX.utils.sheet_to_txt generates UTF16 Formatted Text
        //     XLSX.utils.sheet_to_html generates HTML
        //     XLSX.utils.sheet_to_json generates an array of objects
        //     XLSX.utils.sheet_to_formulae generates a list of formulae
        worksheets[sheetName_1] = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName_1]);
        // console.log(XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]));
    }
    // Show the data as JSON
    // console.log(
    //   "json:\n",
    //   JSON.stringify(worksheets["Ürünlerinizi Burada Listeleyin"]),
    //   "\n\n"
    // );
    // console.log(worksheets["Ürünlerinizi Burada Listeleyin"][0]);
    // Modify the XLSX
    (_a = worksheets[sheetName]).push.apply(_a, resultArray);
    // Update the XLSX file
    // XLSX.utils.sheet_add_json(workbook.Sheets[sheetName], worksheets[sheetName]);
    // XLSX.writeFile(workbook, path);
    // Create a new XLSX file
    var newBook = XLSX.utils.book_new();
    var newSheet = XLSX.utils.json_to_sheet(worksheets[sheetName]);
    XLSX.utils.book_append_sheet(newBook, newSheet, sheetName);
    XLSX.writeFile(newBook, "".concat(path, "\\").concat(mainModalCode, ".xlsx"));
    // [
    //   'Ürünlerinizi Burada Listeleyin',
    //   'Urun_Ozellik_Bilgileri',
    //   'Yardım'
    // ]
}
// I hate both of Trendyol and Hepsiburada but Hepsiburada takes the throne
var fields = {
    "Ürün Adı": "",
    "Satıcı Stok Kodu": "",
    Barkod: "",
    "Varyant Grup Id": "",
    "Ürün Açıklaması": "",
    Marka: "",
    Desi: "",
    KDV: 1,
    "Garanti Süresi (Ay)": 1,
    Görsel1: "",
    Görsel2: "",
    Görsel3: "",
    Görsel4: "",
    Görsel5: "",
    Fiyat: 1,
    Stok: "",
    Video: "",
    "Uyumlu Model": "",
    Renk: "",
    Seçenek: "",
    "Telefon Modeli": "",
    "Uyumlu Marka": "",
    "Garanti Tipi": "",
    "Su Geçirmezlik": "",
    "Ürün  Kodu": "",
    "Malzeme Türü": "",
    "Garanti Tipi2": "",
    "Kılıf Tipi": "",
};
